# Generated by Django 4.1.3 on 2022-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='coolbox_id',
            field=models.ManyToManyField(related_name='coolboxfk', to='coolboxapp.coolbox'),
        ),
    ]
